// clang-format off
#include <scry.hpp>
#include <renderer/diligent_module.hpp>
#include <ecs/components.hpp>
#include <GLFW/glfw3.h>
#include <slint.h>
#include "editor_renderer_bridge.hpp"
#include "editor_window.h" // generated by slint_target_sources
// clang-format on

#include <chrono>

// ---------------------------------------------------------------------------
// EditorLogicModule
// Handles editor-specific DAG tasks (entity picking, transform gizmo, etc.).
// Reactors are scaffolded here; full implementations are incremental.
// ---------------------------------------------------------------------------
namespace {

struct EntitySelectionIntent {
    engine::ecs::Entity target;
};

class EditorLogicModule : public engine::IModule {
public:
    const char* GetName() const override { return "EditorLogicModule"; }

    bool Initialize(engine::Engine& engine) override {
        ENGINE_ASSERT(m_engine == nullptr, "EditorLogicModule::Initialize called twice");
        m_engine = &engine;
        return true;
    }

    void BuildGraph(tf::Taskflow&) override {
        ENGINE_ASSERT(m_engine != nullptr, "BuildGraph called before Initialize()");
    }

    void RegisterReflection() override {
        ENGINE_ASSERT(m_engine != nullptr, "RegisterReflection called before Initialize()");
        using CurrentType = EntitySelectionIntent;
        ENGINE_REFLECT_CLASS(EntitySelectionIntent).ENGINE_REFLECT_FIELD(target);
    }

    void CompileFrameGraph(engine::FrameDAG& dag) override {
        ENGINE_ASSERT(m_engine != nullptr, "CompileFrameGraph called before Initialize()");
        ENGINE_ASSERT(dag.p_write_state != nullptr, "DAG write-state pointer must not be null");
        const int* p_write = dag.p_write_state;

        engine::SystemBuilder(dag)
            .AddIntent("EditorPickingIntent",
                       [this, p_write]() {
                           int write_state = *p_write;
                           m_selectionQueue.Initialize(m_engine->GetFrameArena(write_state), 16);
                           // Future: translate mouse-click world-ray into EntitySelectionIntent
                       })
            .AddReactor("EditorSelectionReactor",
                        engine::Process(m_selectionQueue, [](const EntitySelectionIntent& /*intent*/) {
                            // Future: toggle ecs::SelectionComponent on the target entity
                        }));
    }

    void Shutdown() override {
        ENGINE_ASSERT(m_engine != nullptr, "Shutdown called on module that was never initialized");
        m_engine = nullptr;
    }

private:
    engine::Engine* m_engine = nullptr;
    engine::IntentQueue<EntitySelectionIntent> m_selectionQueue;
};

// ---------------------------------------------------------------------------
// EditorApplication
// ---------------------------------------------------------------------------

class EditorApplication {
public:
    static constexpr uint32_t kViewportWidth = 1024;
    static constexpr uint32_t kViewportHeight = 576;

    bool Initialize() {
        ENGINE_ASSERT(m_renderer == nullptr, "EditorApplication::Initialize called twice");
        // Create the Diligent device window — hidden 1×1 so the Vulkan swap chain
        // has a valid OS surface without producing a visible window.
        if (!m_deviceWindow.Initialize()) {
            return false;
        }
        // Set hints before CreateWindow; hints persist until the next glfwDefaultWindowHints call.
        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
        if (!m_deviceWindow.CreateWindow(1, 1, "SCRY Device")) {
            return false;
        }
        ENGINE_ASSERT(m_deviceWindow.GetRawWindow() != nullptr, "GLFW window handle must be valid after CreateWindow");
        m_inputImpl.Initialize(m_deviceWindow.GetRawWindow());

        auto& renderer = m_engine.RegisterModule<engine::renderer::DiligentModule>();
        m_renderer = &renderer;
        m_engine.RegisterModule<EditorLogicModule>();

        m_engine.GetWindowManager().SetMainWindow(&m_deviceWindow);

        if (!m_engine.Initialize(&m_inputImpl)) {
            return false;
        }

        // VFS is mounted inside Initialize(); build the scene and execution graph
        // before arming the offscreen bridge.
        BuildScene();
        m_engine.RebuildExecutionGraph();

        // Arm offscreen rendering: from this point the render thread routes draw output
        // into the staging texture instead of the (hidden) swap chain.
        ENGINE_ASSERT(kViewportWidth >= 64u, "Viewport width must be at least 64 pixels");
        ENGINE_ASSERT(kViewportHeight >= 64u, "Viewport height must be at least 64 pixels");
        if (!m_bridge.Initialize(*m_renderer, kViewportWidth, kViewportHeight)) {
            return false;
        }

        // Construct the Slint UI window
        m_slintUi = EditorWindow::create();
        ENGINE_ASSERT(m_slintUi.has_value(), "EditorWindow::create() returned an empty handle");

        // Wire the per-frame image push from the bridge into the Slint property.
        // slint::ComponentHandle is reference-counted; capturing a copy here is safe.
        // The setter is cleared by m_bridge.Shutdown() before the engine shuts down.
        slint::ComponentHandle<EditorWindow> uiHandle = *m_slintUi;
        m_bridge.SetImageSetter([uiHandle](slint::Image image) {
            uiHandle->set_viewport_image(std::move(image));
        });

        (*m_slintUi)->show();
        return true;
    }

    void Run() {
        ENGINE_ASSERT(m_renderer != nullptr, "Run() called before Initialize()");
        ENGINE_ASSERT(m_slintUi.has_value(), "Run() called before Slint UI was constructed");
        ENGINE_ASSERT(m_accumulator == 0.0, "Time accumulator must be zero at start of Run()");

        m_engine.InitializeTime();
        const double fixedDt = m_engine.GetTime().GetFixedDeltaTime();
        ENGINE_ASSERT(fixedDt > 0.0, "Fixed timestep must be positive");

        // Drive the engine from within Slint's event loop.  A 1 ms repeated timer keeps
        // the engine running at the fixed-step rate without spinning a separate thread.
        slint::Timer engineTimer(std::chrono::milliseconds(1), [this, fixedDt]() {
            m_engine.GetWindowManager().PollAllEvents();

            auto* mainWindow = m_engine.GetWindowManager().GetMainWindow();
            if (mainWindow != nullptr && !mainWindow->HasFocus()) {
                engine::ITime::Sleep(33);
                m_engine.UpdateTime();
                return;
            }

            m_engine.UpdateTime();
            m_accumulator += m_engine.GetTime().GetDeltaTime();

            while (m_accumulator >= fixedDt) {
                m_engine.Tick();
                m_accumulator -= fixedDt;
            }

            m_engine.SetInterpolationAlpha(m_accumulator / fixedDt);
        });

        // slint::run_event_loop() exits automatically when all Slint windows are hidden/closed.
        slint::run_event_loop();

        // Clear the bridge setter before the engine's destructor joins the render thread,
        // preventing a post-shutdown invoke_from_event_loop delivery.
        m_bridge.Shutdown();
    }

private:
    void BuildScene() {
        auto& reg = m_engine.GetRegistry();

        auto levelEnt = reg.CreateEntity();
        reg.AddComponent<engine::ecs::TagComponent>(levelEnt).tag = engine::StringHash{"Level"};
        reg.AddComponent<engine::ecs::HierarchyComponent>(levelEnt);
        reg.AddComponent<engine::ecs::EnvironmentComponent>(levelEnt);

        // Procedural grid mesh
        auto grid = std::make_shared<engine::io::Mesh>();
        constexpr float kSize = 50.0F;
        constexpr float kStep = 2.0F;
        uint32_t index = 0;
        for (float i = -kSize; i <= kSize; i += kStep) {
            grid->vertices.push_back({{i, 0.0F, -kSize}, {0, 1, 0}, {0.0F, 0.0F}});
            grid->vertices.push_back({{i, 0.0F, kSize}, {0, 1, 0}, {0.0F, 0.0F}});
            grid->indices.push_back(index++);
            grid->indices.push_back(index++);
            grid->vertices.push_back({{-kSize, 0.0F, i}, {0, 1, 0}, {0.0F, 0.0F}});
            grid->vertices.push_back({{kSize, 0.0F, i}, {0, 1, 0}, {0.0F, 0.0F}});
            grid->indices.push_back(index++);
            grid->indices.push_back(index++);
        }
        ENGINE_ASSERT(!grid->vertices.empty(), "Grid mesh must have vertices after procedural construction");
        ENGINE_ASSERT(grid->indices.size() == grid->vertices.size(), "Grid mesh index count must match vertex count (line-list pairs)");

        m_engine.GetResourceManager().GetRawMeshes().load<engine::io::DirectLoader<engine::io::Mesh>>(
            engine::StringHash{"GridMesh"}, engine::io::DirectLoader<engine::io::Mesh>{grid});

        auto gridEnt = reg.CreateEntity();
        reg.AddComponent<engine::ecs::TransformComponent>(gridEnt);
        auto& gridRender = reg.AddComponent<engine::ecs::RenderComponent>(gridEnt);
        gridRender.mesh_id = engine::StringHash{"GridMesh"};
        gridRender.topology = engine::graphics::PrimitiveTopology::LineList;
        auto& gridHier = reg.AddComponent<engine::ecs::HierarchyComponent>(gridEnt);
        gridHier.parent = levelEnt;
        reg.GetComponent<engine::ecs::HierarchyComponent>(levelEnt).first_child = gridEnt;

        auto camEnt = reg.CreateEntity();
        auto& camTrans = reg.AddComponent<engine::ecs::TransformComponent>(camEnt);
        camTrans.matrix(1, 3) = 2.0F;
        camTrans.matrix(2, 3) = -10.0F;
        auto& cam = reg.AddComponent<engine::ecs::CameraComponent>(camEnt);
        const float aspect =
            static_cast<float>(kViewportWidth) / static_cast<float>(kViewportHeight);
        ENGINE_ASSERT(cam.fov > 0.0F && cam.fov < 180.0F, "Camera FOV must be in (0, 180) degrees");
        ENGINE_ASSERT(aspect > 0.0F, "Viewport aspect ratio must be positive");
        cam.view_proj =
            engine::math::PerspectiveFovLH(engine::math::DegToRad(cam.fov), aspect, cam.near_plane, cam.far_plane);
    }

    engine::Engine m_engine;
    engine::GlfwWindow m_deviceWindow;
    engine::GlfwInput m_inputImpl;
    engine::renderer::DiligentModule* m_renderer = nullptr;
    editor::RendererBridge m_bridge;
    std::optional<slint::ComponentHandle<EditorWindow>> m_slintUi;
    double m_accumulator = 0.0;
};

} // namespace

int main() {
    EditorApplication app;
    if (!app.Initialize()) {
        return -1;
    }
    app.Run();
    return 0;
}
