#ifndef ENGINE_CORE_HPP
#define ENGINE_CORE_HPP

#include "debug/assert.h"
#include "OS/window_manager.hpp"
#include "OS/glfw/glfw_window.hpp"
#include "OS/glfw/glfw_input.hpp"
#include "OS/keys.hpp"
#include "OS/types.h"
#include "IO/vfs.hpp"
#include "IO/threading/job_system.hpp"
#include "memory/chained_arena.hpp"
#include "memory/block_pool.hpp"
#include "math/math.h"
#include "memory/array.hpp"
#include "memory/tracked_heap.hpp"
#include "time/ITime.hpp"
#include "engine.hpp"
#include "reflection/core_reflection.hpp"
#include "reflection/builder.hpp"
#include "module/module.hpp"
#include "module/system_builder.hpp"
#include "ecs/ecs_types.hpp"
#include "ecs/ecs_allocator.hpp"
#include "ecs/registry.hpp"
#include "IO/asset_types.h"
#include "IO/manager.hpp"
#include "serialization/archive.hpp"
#include "serialization/meta_serializer.hpp"

#endif // ENGINE_CORE_HPP
